Demo.PL/ViewModels/CourseResultViewModel.cs
using Demo.DAL.Entities;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace Demo.PL.ViewModels
{
    public class CourseResultViewModel
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "*")]
        [Range(0, 100, ErrorMessage = "{0} must be {1} to {2}")]
        public int Degree { get; set; }
        [DisplayName("Course")]
        public int? crs_id { get; set; }
        [DisplayName("Trainee")]
        public int? trainee_id { get; set; }
        public Course course { get; set; }
        public Trainee Trainee { get; set; }
    }
}

Demo.PL/Controllers/CourseController.cs
using Demo.BLL.Interfaces;
using Demo.DAL.Entities;
using Demo.PL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Demo.PL.Controllers
{
    public class CourseController : Controller
    {
        private readonly ICourseRepository _courseRepository;
        private readonly IDepartmentRepository _departmentRepository;

        public CourseController(
            ICourseRepository courseRepository,
            IDepartmentRepository departmentRepository
            )
        {
            _courseRepository = courseRepository;
            _departmentRepository = departmentRepository;
        }

        public IActionResult CheckGradeAsync(int MinDegree, int Grade)
        {
            if (MinDegree <= Grade)
            {
                return Json(true);
            }
            return Json(false);
        }
        public async Task<IActionResult> GetCoursePerDepartment(int deptID)
        {
            var courses = await _courseRepository.GetCoursePerDepartmentAsync(deptID);
            return Json(courses);
        }
        public async Task<IActionResult> Index()
        {
            var GetAllCourses = await _courseRepository.GetAllAsync();
            return View(GetAllCourses);
        }
        public async Task<IActionResult> Details(int id)
        {
            var course = await _courseRepository.GetCourseAsync(id);
            CourseViewModel courseVM = new()
            {
                Id = course.Id,
                Name = course.Name!,
                Grade = course.Grade,
                MinDegree = course.MinDegree,
                dept_id = course.dept_id
            };
            ViewBag.DeptName = await _departmentRepository.GetDepartmentAsync(course.dept_id);
            return View(courseVM);
        }
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Add()
        {
            ViewBag.DeptDropDownList = await _departmentRepository.GetDepartmentsAsync();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Add(CourseViewModel courseVM)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    ViewBag.DeptDropDownList = await _departmentRepository.GetDepartmentsAsync();
                    return View();
                }
                var course = new Course
                {
                    Id = courseVM.Id,
                    Name = courseVM.Name,
                    Grade = courseVM.Grade,
                    MinDegree = courseVM.MinDegree,
                    dept_id = courseVM.dept_id
                };

                await _courseRepository.AddCourseAsync(course);
                TempData["successMessageForAddingCourse"] = "Course Added successfully!";
            }
            catch
            {
                return View();
            }
            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int id)
        {
            await _courseRepository.DeleteCourseAsync(id);
            TempData["successMessageForDeleteCourse"] = "Course deleted successfully!";
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id)
        {
            var course = await _courseRepository.GetCourseAsync(id);
            ViewBag.DeptDropDownList = await _departmentRepository.GetDepartmentsAsync();
            CourseViewModel courseVM = new()
            {
                Name = course.Name!,
                Grade = course.Grade,
                MinDegree = course.MinDegree,
                dept_id = course.dept_id,
            };
            return View(courseVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, CourseViewModel courseVM)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    ViewBag.DeptDropDownList = await _departmentRepository.GetDepartmentsAsync();
                    return View();
                }
                var course = new Course
                {
                    Id = id,
                    Name = courseVM.Name,
                    Grade = courseVM.Grade,
                    MinDegree = courseVM.MinDegree,
                    dept_id = courseVM.dept_id
                };
                await _courseRepository.UpdateCourseAsync(course);
                TempData["successMessageForUpdateCourse"] = "Course updated successfully!";
            }
            catch
            {
                return View();
            }
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Search(string searchString)
        {
            var Search = await _courseRepository.SearchCourseAsync(searchString);
            ViewBag.Search = searchString;
            return View(Search);
        }

    }
}

Demo.PL/Controllers/TrainerController.cs
using Demo.BLL.Interfaces;
using Demo.DAL.Entities;
using Demo.PL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace Demo.PL.Controllers
{
    public class TrainerController : Controller
    {
        private readonly ITrainerRepository _trainerRepository;
        private readonly IDepartmentRepository _departmentRepository;
        private readonly ICourseRepository _courseRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public TrainerController(
            ITrainerRepository trainerRepository,
            IDepartmentRepository departmentRepository,
            ICourseRepository courseRepository,
            IWebHostEnvironment webHostEnvironment
            )
        {
            _trainerRepository = trainerRepository;
            _departmentRepository = departmentRepository;
            _courseRepository = courseRepository;
            _webHostEnvironment = webHostEnvironment;
        }
        public async Task<IActionResult> Index()
        {
            var trainers = await _trainerRepository.GetAllAsync();
            return View(trainers);
        }
        public async Task<IActionResult> Details(int id)
        {
            var trainer = await _trainerRepository.GetTraineeAsync(id);
            if (trainer == null)
            {
                return NotFound();
            }
            TrainerViewModel trainerView = new()
            {
                Id = trainer.Id,
                Name = trainer.Name!,
                Address = trainer.Address,
                PhoneNumber = trainer.PhoneNumber,
                Level = trainer.Level,
                ImageUrl = trainer.ImageUrl,
                dept_id = trainer.dept_id

            };
            ViewBag.DeptName = await _departmentRepository.GetDepartmentAsync(trainer.dept_id);
            return View(trainerView);
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Instructor")]
        public async Task<IActionResult> Add()
        {
            ViewBag.DeptDropDownList = await _departmentRepository.GetDepartmentsAsync();
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Instructor")]

        public async Task<IActionResult> Add(TrainerViewModel trainerVM)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (!ModelState.IsValid)
                    {
                        ViewBag.DeptDropDownList = await _departmentRepository.GetDepartmentsAsync();
                        return View();
                    }
                    #region  Image 
                    trainerVM.ImageUrl = "Images/TraineePhotos/" + Guid.NewGuid().ToString();
                    trainerVM.ImageUrl += trainerVM.File.FileName;
                    string serverFolder = Path.Combine(_webHostEnvironment.WebRootPath, trainerVM.ImageUrl);
                    //await traineevm.File.CopyToAsync(new FileStream(serverFolder, FileMode.Create));
                    using (FileStream fs = new FileStream(serverFolder, FileMode.Create))
                    {
                        trainerVM.File?.CopyTo(fs);
                    }
                    ;

                    #endregion
                    var trainee = new Trainee
                    {
                        Name = trainerVM.Name,
                        Address = trainerVM.Address,
                        PhoneNumber = trainerVM.PhoneNumber,
                        Level = trainerVM.Level,
                        ImageUrl = trainerVM.ImageUrl,
                        dept_id = trainerVM.dept_id
                    };
                    await _trainerRepository.AddTraineeAsync(trainee);
                    TempData["successMessageForAddingTrainee"] = "Trainee Added successfully!";
                }
                catch
                {
                    return View();
                }
                
            }
            return RedirectToAction(nameof(Index));
            
        }

        [HttpGet]
        [Authorize(Roles = "Admin,Instructor")]

        public async Task<IActionResult> Delete(int id)
        {
            string oldFileName = (await _trainerRepository.GetTraineeAsync(id)).ImageUrl!;
            string fullOldPath = Path.Combine(_webHostEnvironment.WebRootPath, oldFileName);
            System.IO.File.Delete(fullOldPath);
            await _trainerRepository.DeleteTraineeAsync(id);
            TempData["successMessageForDeleteTrainee"] = "Trainee deleted successfully!";
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        [Authorize(Roles = "Admin,Instructor")]

        public async Task<IActionResult> Edit(int id)
        {
            var trainer = await _trainerRepository.GetTraineeAsync(id);
            if (trainer == null)
            {
                return NotFound();
            }
            TrainerViewModel trainerVM = new()
            {
                Id = trainer.Id,
                Name = trainer.Name!,
                Address = trainer.Address,
                PhoneNumber = trainer.PhoneNumber,
                Level = trainer.Level,
                ImageUrl = trainer.ImageUrl,
                dept_id = trainer.dept_id
            };
            ViewBag.DeptDropDownList = await _departmentRepository.GetDepartmentsAsync();
            return View(trainerVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Instructor")]

        public async Task<IActionResult> Edit(TrainerViewModel traineeVM)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.DeptDropDownList = await _departmentRepository.GetDepartmentsAsync();
                return View();
            }
            #region  Image
            var oldUrl = traineeVM.ImageUrl;
            traineeVM.ImageUrl = "Images/TraineePhotos/";
            traineeVM.ImageUrl = traineeVM.File?.FileName;
            string fullPath = Path.Combine(_webHostEnvironment.WebRootPath, traineeVM.ImageUrl!);
            if (traineeVM.ImageUrl != oldUrl)
            {
                traineeVM.ImageUrl = "Images/TraineePhotos/" + Guid.NewGuid().ToString();
                traineeVM.ImageUrl += traineeVM.File?.FileName;
                string fullPath2 = Path.Combine(_webHostEnvironment.WebRootPath, traineeVM.ImageUrl!);
                string oldFileName = (await _trainerRepository.GetTraineeAsync(traineeVM.Id)).ImageUrl!;
                string fullOldPath = Path.Combine(_webHostEnvironment.WebRootPath, oldFileName);
                if (fullPath2 != fullOldPath)
                {
                    using (FileStream fs = new FileStream(fullPath2, FileMode.Create))
                    {
                        System.IO.File.Delete(fullOldPath);
                        traineeVM.File?.CopyTo(fs);
                    }
                }
            }

            #endregion
            var trainee = new Trainee
            {
                Id = traineeVM.Id,
                Name = traineeVM.Name,
                Address = traineeVM.Address,
                PhoneNumber = traineeVM.PhoneNumber,
                Level = traineeVM.Level,
                ImageUrl = traineeVM.ImageUrl,
                dept_id = traineeVM.dept_id
            };
            await _trainerRepository.UpdateTraineeAsync(trainee);
            TempData["successMessageForEditTrainee"] = "Trainee Updated successfully!";
            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = "Admin,Instructor")]

        public async Task<IActionResult> Search(string searchString)
        {
            var Search = await _trainerRepository.SearchTraineeAsync(searchString);
            return View(Search);
        }
    }
}

Demo.PL/Views/CourseResult/Add.cshtml
@model CourseResultViewModel
@{
    ViewData["Title"] = "Add";
    SelectList Traineeitems = new SelectList(ViewBag.TraineeName, "Id", "Name");
    SelectList Coursesitems = new SelectList(ViewBag.CourseName, "Id", "Name");
    Layout = "~/Views/Shared/_OperationLayout.cshtml";
}
<div class="card card-header">
    <h1 class="text-center m-5" style="color:burlywood">Adding New TraineeResult</h1>
    <form asp-action="Create" method="post">
        @* <div> *@
        @*     <label asp-for="trainee_id" class="m-1"></label> *@
        @*     <span asp-validation-for="trainee_id" class="text-danger"></span> *@
        @*     <select class="form-select" asp-for="trainee_id" asp-items="Traineeitems"><option>--Select Trainee--</option></select> *@
        @* </div> *@
        @* <div> *@
        @*     <label asp-for="crs_id" class="m-1"></label> *@
        @*     <span asp-validation-for="crs_id" class="text-danger"></span> *@
        @*     <select class="form-select" asp-for="crs_id" asp-items="Coursesitems"><option>--Select Course--</option></select> *@
        @* </div> *@

        <div>
            <label asp-for="trainee_id" class="m-1"></label>
            <span asp-validation-for="trainee_id" class="text-danger"></span>
            <select id="trainee_id" class="form-select" asp-for="trainee_id" asp-items="Traineeitems" onchange="loadCoursesByTrainee()">
                <option value="">--Select Trainee--</option>
            </select>
        </div>

        <div> 
            <label asp-for="crs_id" class="m-1"></label> 
            <span asp-validation-for="crs_id" class="text-danger"></span> 
            <select id="crs_id" class="form-select" asp-for="crs_id"> 
                <option value="">--Select Course--</option> 
            </select> 
        </div> 
        <div>
            <label asp-for="Degree" class="m-1"></label>
            <span asp-validation-for="Degree" class="text-danger"></span>
            <input class="form-control" asp-for="Degree" />
        </div>
        <br />
        <div class="card-footer text-center">
            <button class="btn btn-success w-25" asp-fragment="#">Add</button>
            <a asp-action="Index" asp-fragment="#" class="btn btn-primary w-25">Cancel</a>
        </div>

    </form>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
	<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
	<script src="~/js/validation.js"></script>
    <script>
        function loadCoursesByTrainee() {
            const traineeId = document.getElementById("trainee_id").value;

            if (traineeId) {
                $.ajax({
                    url: '/CourseResult/GetCoursesForTrainee',
                    type: 'GET',
                    data: { traineeId: traineeId },
                    success: function (courses) {
                        const courseSelect = document.getElementById("crs_id");
                        courseSelect.innerHTML = '<option value="">--Select Course--</option>';

                        for (const course of courses) {
                            const option = document.createElement("option");
                            option.value = course.id;
                            option.text = course.name;
                            courseSelect.appendChild(option);
                        }
                    },
                    error: function () {
                        alert("Could not load courses for this trainee.");
                    }
                });
            }
        }
    </script>

}

Demo.PL/Views/CourseResult/Edit.cshtml
@model CourseResultViewModel
@{
    ViewData["Title"] = "Edit";
    SelectList Traineeitems = new SelectList(ViewBag.TraineeName, "Id", "Name");
    SelectList Coursesitems = new SelectList(ViewBag.CourseName, "Id", "Name");
    Layout = "~/Views/Shared/_OperationLayout.cshtml";
}
<div class="card card-header">
    <h1 class="text-center m-5" style="color:burlywood">Updating TraineeResult</h1>
    <form asp-action="Edit" method="post">
        <div>
            <label asp-for="trainee_id" class="m-1"></label>
            <span asp-validation-for="trainee_id" class="text-danger"></span>
            <select class="form-select" asp-for="trainee_id" asp-items="Traineeitems"></select>
        </div>
        <div>
            <label asp-for="crs_id" class="m-1"></label>
            <span asp-validation-for="crs_id" class="text-danger"></span>
            <select class="form-select" asp-for="crs_id" asp-items="Coursesitems"></select>
        </div>

        <div>
            <label asp-for="Degree" class="m-1"></label>
            <span asp-validation-for="Degree" class="text-danger"></span>
            <input asp-for="Degree" class="form-control">
        </div><br />

        <div class="card-footer text-center">
            <button class="btn btn-success w-25" asp-fragment="#" onclick="return confirm('Are you Sure to Update ?')">Update</button>
            <a asp-action="ShowAll" asp-fragment="#" class="btn btn-primary w-25">Cancel</a>
        </div>

    </form>
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

Demo.PL/Views/CourseResult/Index.cshtml
@model List<CourseResult>
@{
    ViewData["Title"] = "Index";
	var courseResult = Model;
    Layout = "~/Views/Shared/_IndexLayout.cshtml";
}
<hr />
<h2 class="text-center" id="#">@courseResult.Count Results</h2>
<hr>
@if (!Model.Any())
{
	<div class="alert alert-warning">Nothing added yet!</div>
	 @if (User.IsInRole("Admin") || User.IsInRole("Instructor")) 
	{ 
		<div class="text-center ">
			<a asp-action="Add" class="bi bi-pen btn btn-success">Add new Result</a>
		</div>
	 } 
}
else
{
	<div class="container-xl">
		<div class="table-responsive">
			<div class="table-wrapper">
				<table class="table table-hover  table-bordered m-4 fw-bold table-striped" style="background-color:lightgray">
					<tr>
						<th colspan="4"> <h2 style="color:darkred">Manage Results</h2></th>
						<th>
							 @if (User.IsInRole("Admin") || User.IsInRole("Instructor")) 
							 { 
								<div class="text-center">
									<a asp-action="Search" class="btn fw-bold btn-outline-dark">Search</a>
									<a asp-action="Add" class="bi bi-pen btn btn-success">Add new Result</a>
								</div>
							 } 
						</th>
					</tr>
					<tr style="font-size:17px">
						<th class="text-center">#</th>
						<th class="text-center">Trainee</th>
						<th class="text-center">Course</th>
						<th class="text-center">Degree</th>
						<th colspan="2" class="text-center">Action</th>
					</tr>
					@for (int i = 0; i < courseResult.Count; i++)
					{
						<tr class="text-center">
							<td>@courseResult[i].trainee_id</td>
							<td><a style="font-family:Courier New, Courier, monospace ;color:brown" asp-controller="Trainer" asp-action="Details" asp-route-id="@courseResult[i].Trainee?.Id">@courseResult[i].Trainee?.Name</a></td>
							<td><a style="font-family:Courier New, Courier, monospace;;color:brown" asp-controller="Course" asp-action="Details" asp-route-id="@courseResult[i].Course?.Id" style="background-color:cadetblue">@courseResult[i].Course?.Name</a></td>

							@if (courseResult[i].Degree >= 60)
							{
								<td style="color:darkgreen">@courseResult[i].Degree %</td>
							}
							else
							{
								<td style="color:red">@courseResult[i].Degree %</td>
							}
							<td>
								 @if (User.IsInRole("Admin") || User.IsInRole("Instructor"))
								 { 
									<a asp-action="Edit" asp-route-id="@courseResult[i].Id" class="bi bi-pencil btn btn-warning btn-sm" aria-hidden="true">Edit</a>
									<a asp-action="Delete" asp-route-id="@courseResult[i].Id" asp-fragment="#" class="bi bi-trash btn btn-danger btn-sm" aria-hidden="true" onclick="return confirm('Are you Sure to delete ?')">Delete</a>
								 } 
							</td>
						</tr>
					}
				</table>
			</div>
		</div>
	</div>
}

Demo.PL/Views/CourseResult/Results.cshtml
@model List<CourseResult>
@{
    ViewData["Title"] = "Results";
	var courseResult = Model;
    Layout = "~/Views/Shared/_OperationLayout.cshtml";
}

<h2 class="text-center">@courseResult.Count Result</h2>
<hr>
@if (!Model.Any())
{
	<div class="alert alert-warning">Nothing added yet!</div>
	 @if (User.IsInRole("Admin") || User.IsInRole("Instructor")) 
	 { 
		<div class="text-center ">
			<a class="btn btn-success" asp-action="Add">Add new Result</a>
		</div>
	} 
}
else
{
	<div>
		<div class="text-center "><a class="btn btn-success" asp-action="Create">Add new Result</a></div>
		<table class="table table-hover  table-bordered m-4 fw-bold table-striped" style="background-color:lightgray">
			<tr>
				<th>#</th>
				<th>Course</th>
				<th>Degree</th>
			</tr>
			@for (int i = 0; i < courseResult.Count; i++)
			{
				<tr class="text-center">
					<td>@(i + 1)</td>
					<td style="font-family:Courier New, Courier, monospace">@(courseResult[i]?.Course?.Name ?? "Not Assign")</td>
					@if (courseResult[i].Degree >= 60)
					{
						<td style="color:forestgreen">@courseResult[i].Degree%</td>
					}
					else
					{
						<td style="color:red">@courseResult[i].Degree%</td>
					}
				</tr>
			}

		</table>
		<hr>
	</div>
}

Demo.PL/Views/CourseResult/Search.cshtml
@model List<CourseResult>
@{
    ViewData["Title"] = "Search";
	var courseRT = Model;
    Layout = "~/Views/Shared/_OperationLayout.cshtml";
}
<h1> Search by name :</h1>
<form asp-action="Search">
	<div class="form-group">
		<label>Search :</label>
		<input type="text" name="SearchString" />
		<input type="submit" asp-action="Search" value="Search" class="btn btn-primary" /><br />
		@if (Model.Any())
		{
			<table class="table table-hover  table-bordered m-4 fw-bold table-striped">
				<thead>
					<tr>
						<th>#</th>
						<th>Name</th>
						<th>Course</th>
						<th>Degree</th>
					</tr>
				</thead>
				<tbody>
					@for (int i = 0; i < courseRT.Count; i++)
					{
						<tr>
							<td>@(i + 1)</td>
							<td>@courseRT[i].Trainee?.Name</td>
							<td>@courseRT[i].Course?.Name</td>
							@if (courseRT[i].Degree >= 60)
							{
								<td style="color:forestgreen">@courseRT[i].Degree%</td>
							}
							else
							{
								<td style="color:red">@courseRT[i].Degree%</td>
							}
						</tr>
					}
				</tbody>
			</table>
			<br />
		}
		else
		{
			<br>
			<div class="alert alert-warning">There are no items!</div>
		}
	</div>
</form>
<br />
<br />
<div class="text-center"><a asp-action="Index" asp-fragment="#" class="btn btn-success">Return back</a></div>